name: Bootstrap ArgoCD
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
permissions:
    id-token: write
    contents: read   

jobs:
  install-argocd:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bootstrap repo
        uses: actions/checkout@v3

      - name : Install CA for AWS eks
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ACTION_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Configure kubeconfig
        run: |
          export KUBERNETES_CLUSTER_NAME=${{secrets.KUBERNETES_CLUSTER_NAME}}
          export AWS_REGION=${{secrets.AWS_REGION}}
          aws eks update-kubeconfig --region $AWS_REGION --name $KUBERNETES_CLUSTER_NAME
          kubectl get nodes

      - name: Install the ingress-controller
        run: |
          helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace


      - name: Install ArgoCD CLI
        run: |
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/argocd    
      
      - name: Install ArgoCD and Add gitops to ArgoCD
        run: |
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
          export TOKEN=${{secrets.TOKEN}}
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update

          helm upgrade --install argocd argo/argo-cd \
          argocd repo add  $GITOPS_URL \
            --username ${{ secrets.DOCKER_USERNAME }} \
            --password ${{ secrets.TOKEN }}


      - name: Wait for ArgoCD pods
        run: kubectl wait --for=condition=available --timeout=300s deployment -n feedback --all
      
  Deploy :
    environment: staging
    needs: install-argocd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bootstrap repo
        uses: actions/checkout@v3

      - name : Install CA for AWS eks
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ACTION_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Configure kubeconfig
        run: |
          export KUBERNETES_CLUSTER_NAME=${{secrets.KUBERNETES_CLUSTER_NAME}}
          export AWS_REGION=${{secrets.AWS_REGION}}
          aws eks update-kubeconfig --region $AWS_REGION --name $KUBERNETES_CLUSTER_NAME
          kubectl get nodes
          kubectl config get-contexts

      - name: ArgoCD login
        run: |
          export ARGOCD_ADMIN_PASSWORD=${{secrets.ARGOCD_ADMIN_PASSWORD}}
          kubectl port-forward svc/argocd-server -n feedback 8080:443 &  sleep 5 
          argocd login localhost:8080 --insecure --username admin --password ${{ secrets.ARGOCD_ADMIN_PASSWORD }}
  

      - name : pull application.yaml file
        run: |
          export BRANCH=${{secrets.BRANCH}}
          export MENIFEST_REPO=${{secrets.MENIFEST_REPO}}
          export TOKEN=${{secrets.TOKEN}}
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
          mkdir -p ~/agrocd 

          sudo apt-get update && sudo apt-get install -y git
          git clone --branch $BRANCH https://$TOKEN@github.com/$DOCKER_USERNAME/$MENIFEST_REPO.git  ~/agrocd 
            
      - name: kubectl apply run applications
        run: | 
          cd  ~/agrocd 
          kubectl apply -f applications/feedback.ingress.staging.yaml
          kubectl wait --for=condition=ready --timeout=300s -n ingress-nginx deployment/nginx-ingress-controller
          kubectl apply -f applications/feedback.certmanager.staging.yaml
          kubectl apply -f applications/feedback.kafka-cluster.staging.yaml
          kubectl wait kafka/kafka-prod --for=condition=Ready --timeout=300s -n kafka
          kubectl apply -f applications/feedback.services.staging.yaml

