name: Bootstrap ArgoCD
on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging
permissions:
    id-token: write
    contents: read   

jobs:
  install-argocd:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bootstrap repo
        uses: actions/checkout@v3

      - name : Install CA for AWS eks
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ACTION_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name: Configure kubeconfig
        run: |
          
          export KUBERNETES_CLUSTER_NAME=${{secrets.KUBERNETES_CLUSTER_NAME}}
          export AWS_REGION=${{secrets.AWS_REGION}}
          aws eks update-kubeconfig --region $AWS_REGION --name $KUBERNETES_CLUSTER_NAME
          kubectl get nodes

      - name: Install the ingress-controller
        run: |
          helm upgrade --install ingress-nginx ingress-nginx --repo https://kubernetes.github.io/ingress-nginx --namespace ingress-nginx --create-namespace

      
      - name: Install ArgoCD and Add gitops to ArgoCD
        run: |
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
          export TOKEN=${{secrets.TOKEN}}
          export ARGOCD_PASSWORD=${{secrets.ARGOCD_ADMIN_PASSWORD}}
          helm repo add argo https://argoproj.github.io/argo-helm
          helm repo update
          helm uninstall argocd --namespace feedback --ignore-not-found
          helm install argocd argo/argo-cd --namespace feedback \
          --create-namespace

      - name: Wait for ArgoCD pods
        run: kubectl wait --for=condition=available --timeout=300s deployment -n feedback --all
      
  Deploy :
    environment: staging
    needs: install-argocd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bootstrap repo
        uses: actions/checkout@v3
      
      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
          kubectl version --client

      - name : Install CA for AWS eks
        run: |
          sudo apt-get update && sudo apt-get install -y ca-certificates

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.ACTION_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Configure kubeconfig
        run: |
          export KUBERNETES_CLUSTER_NAME=${{secrets.KUBERNETES_CLUSTER_NAME}}
          export AWS_REGION=${{secrets.AWS_REGION}}
          aws eks update-kubeconfig --region $AWS_REGION --name $KUBERNETES_CLUSTER_NAME
          kubectl get nodes
          kubectl config get-contexts
      
      - name: Install ArgoCD CLI and agrocd
        run: |
          kubectl apply -n feedback -f https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.8/manifests/ha/install.yaml
          curl -sSL -o argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv argocd /usr/local/bin/

      # - name : create scripts/create-secrets.sh
      #   run : |
      #     mkdir -p scripts
      #     touch scripts/create-secrets.sh
      #     cat << 'EOF' > scripts/create-secrets.sh
      #     set e
      #     kubectl -n $ARGOCD_NAMESPACE apply -f - <<EOF
      #     apiVersion: v1
      #     kind: ConfigMap
      #     metadata:
      #       name: argocd-cm
      #       namespace: $ARGOCD_NAMESPACE
      #     data:
      #       dex.config: |
      #         connectors:
      #         - type: github
      #           id: github
      #           name: GitHub
      #           config:
      #             clientID: $GITHUB_CLIENT_ID
      #             clientSecret: $GITHUB_CLIENT_SECRET
      #             orgs:
      #             - name: $ORGS_NAME
      #               teams:
      #                 - dev-team
      #     EOF
      #     chmod +x scripts/create-secrets.sh

      # - name: Verify Group credentials
      #   env:
      #     ARGOCD_NAMESPACE=feedback
      #     GITHUB_CLIENT_ID=${{secrets.ARGO_CLIENT_ID}}
      #     GITHUB_CLIENT_SECRET=${{secrets.ARGO_CLIENT_SECRETCLIENT_SECRET}}
      #     ORGS_NAME=${{secrets.DOCKER_USERNAME}}
      #   run: |
      #     bash scripts/create-secrets.sh 
      - name : Add metric argocd-server
        run : |
             helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/
             helm upgrade --install metrics-server metrics-server/metrics-server --namespace kube-system \
             --set image.repository=registry.k8s.io/metrics-server/metrics-server \
             --set image.tag=v0.7.2 \
             --set "args={--kubelet-insecure-tls,--kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname}"

      - name: ArgoCD login
        run: |
          export ARGOCD_ADMIN_PASSWORD=$(printf "%s" "${{secrets.ARGOCD_ADMIN_PASSWORD}}" | htpasswd -Bn -i -)
          export GITOPS_URL=${{secrets.GITOPS_URL}}
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
          export TOKEN=${{secrets.TOKEN}}

          kubectl patch secret argocd-secret -n feedback -p '{"data": {"admin.password": null, "admin.passwordMtime": null}}'

          kubectl rollout restart deployment argocd-server -n feedback

          kubectl -n feedback get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

          kubectl port-forward svc/argocd-server -n feedback 8080:443 &  sleep 5 

          export ARGOCD_OPTS='--port-forward-namespace feedback'

          ARGOCD_NAMESPACE="feedback"

          INITIAL_PASSWORD=$(kubectl -n "$ARGOCD_NAMESPACE" get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d)

          argocd login localhost:8080 --insecure --username admin --password $INITIAL_PASSWORD

          argocd repo add  $GITOPS_URL \
            --username $DOCKER_USERNAME \
            --password $TOKEN --upsert
  

      - name : pull application.yaml file
        run: |
          export BRANCH=${{secrets.BRANCH}}
          export MANIFEST_REPO=${{secrets.MANIFEST_REPO}}
          export TOKEN=${{secrets.TOKEN}}
          export DOCKER_USERNAME=${{secrets.DOCKER_USERNAME}}
 
          sudo apt-get update && sudo apt-get install -y git
          mkdir -p ~/argocd
          git clone --branch $BRANCH https://$TOKEN@github.com/$DOCKER_USERNAME/$MANIFEST_REPO.git  ~/argocd     
     
      - name : Install helm charts
        run: |
           helm repo add bitnami https://charts.bitnami.com/bitnami
           helm repo update

      - name: kubectl apply run applications
        run: | 
          cd  ~/argocd
          kubectl apply -f aplications/project/rbac.app.yaml -n argocd
          kubectl apply -f applications/project/secrets.app.yaml -n feedback
          kubectl apply -f applications/manifest/secrets.yaml -n feedback
          kubectl apply -f applications/project/kafka-cluster.app.yaml -n feedback
          kubectl apply -f applications/project/reach-frontend.app.yaml -n feedback
          kubectl apply -f applications/project/reach-backend.app.yaml -n feedback
          kubectl apply -f applications/project/reach-ws-server.app.yaml -n feedback
          kubectl apply -f applications/project/reach-consumer1.app.yaml -n feedback
          kubectl apply -f applications/project/reach-consumer2.app.yaml -n feedback 
          kubectl apply -f applications/project/ingress.app.yaml -n feedback

          
          kubectl rollout restart deployment  -n feedback
          kubectl rollout restart deployment  -n feedback-services
          kubectl rollout restart deployment  -n kafka



